export const SET_SETTING_DRAW_LINE_DURATION = "SET_SETTING_DRAW_LINE_DURATION";
export const SET_SETTING_PLACEMENT_EFFECT = "SET_SETTING_PLACEMENT_EFFECT";
export const SET_SETTING_LAST_PIECE_EMPHASIZED = "SET_SETTING_LAST_PIECE_EMPHASIZED";
