export { default as RelatiGame } from "./RelatiGame";
export type { Props as RelatiGameProps } from "./RelatiGame";
export { default as RelatiBoard } from "./RelatiBoard";
export type { Props as RelatiBoardProps } from "./RelatiBoard";
export { default as RelatiPiece } from "./RelatiPiece";
export type { Props as RelatiPieceProps } from "./RelatiPiece";
export { default as RelatiTutorialX5 } from "./RelatiTutorialX5";
export type { Props as RelatiTutorialX5Props } from "./RelatiTutorialX5";
export { default as RelatiTutorialX7 } from "./RelatiTutorialX7";
export type { Props as RelatiTutorialX7Props } from "./RelatiTutorialX7";
export { default as RelatiTutorialX9 } from "./RelatiTutorialX9";
export type { Props as RelatiTutorialX9Props } from "./RelatiTutorialX9";
