export { default as GameLeaveMessageBox } from "./GameLeaveMessageBox";
export type { Props as GameLeaveMessageBoxProps } from "./GameLeaveMessageBox";
export { default as GameOverMessageBox } from "./GameOverMessageBox";
export type { Props as GameOverMessageBoxProps } from "./GameOverMessageBox";
export { default as GameWaitMatchMessageBox } from "./GameWaitMatchMessageBox";
export type { Props as GameWaitMatchMessageBoxProps } from "./GameWaitMatchMessageBox";
export { default as RelatiGameBy0Player } from "./RelatiGameBy0Player";
export { default as RelatiGameBy1Player } from "./RelatiGameBy1Player";
export { default as RelatiGameBy2Player } from "./RelatiGameBy2Player";
export { default as RelatiGameBy2PlayerOnline } from "./RelatiGameBy2PlayerOnline";
export * from "./types";
