#ifndef __COLOR_H__
#define __COLOR_H__

#define COLOR_RESET "\x1b[0m"
#define COLOR_FG_BLACK "\x1b[30m"
#define COLOR_FG_RED "\x1b[31m"
#define COLOR_FG_GREEN "\x1b[32m"
#define COLOR_FG_YELLOW "\x1b[33m"
#define COLOR_FG_BLUE "\x1b[34m"
#define COLOR_FG_MAGENTA "\x1b[35m"
#define COLOR_FG_CYAN "\x1b[36m"
#define COLOR_FG_WHITE "\x1b[37m"
#define COLOR_BG_BLACK "\x1b[40m"
#define COLOR_BG_RED "\x1b[41m"
#define COLOR_BG_GREEN "\x1b[42m"
#define COLOR_BG_YELLOW "\x1b[43m"
#define COLOR_BG_BLUE "\x1b[44m"
#define COLOR_BG_MAGENTA "\x1b[45m"
#define COLOR_BG_CYAN "\x1b[46m"
#define COLOR_BG_WHITE "\x1b[47m"
#define COLOR_FG_BRIGHT_BLACK "\x1b[90m"
#define COLOR_FG_BRIGHT_RED "\x1b[91m"
#define COLOR_FG_BRIGHT_GREEN "\x1b[92m"
#define COLOR_FG_BRIGHT_YELLOW "\x1b[93m"
#define COLOR_FG_BRIGHT_BLUE "\x1b[94m"
#define COLOR_FG_BRIGHT_MAGENTA "\x1b[95m"
#define COLOR_FG_BRIGHT_CYAN "\x1b[96m"
#define COLOR_FG_BRIGHT_WHITE "\x1b[97m"
#define COLOR_BG_BRIGHT_BLACK "\x1b[100m"
#define COLOR_BG_BRIGHT_RED "\x1b[101m"
#define COLOR_BG_BRIGHT_GREEN "\x1b[102m"
#define COLOR_BG_BRIGHT_YELLOW "\x1b[103m"
#define COLOR_BG_BRIGHT_BLUE "\x1b[104m"
#define COLOR_BG_BRIGHT_MAGENTA "\x1b[105m"
#define COLOR_BG_BRIGHT_CYAN "\x1b[106m"
#define COLOR_BG_BRIGHT_WHITE "\x1b[107m"

#endif
